### ISSUE TITLE
Deliverable 1:  Project Specification

### ISSUE THREAD

**Issue by cbondurant** [Berea-CS-Courses/capstone-project-cbondurant#3]
Project specification of Lipuma needs to be made.

__I would like feedback on ...__ 
- Is this an acceptable list of goals? I wanted to make more than might be possible within the time frame, so that I would have enough goals to focus on throughout the semester.

**Comment by walkerje** [comment]
Great differentiation between in-scope and out-of-scope, as well as a succinct definition of the project itself. Be sure to consider non-functional and functional requirements (e.g, must run on web-browsers vs must run on any major desktop platform). It would be effective to clarify intended usages, as they seem mixed at the current stage of development. Some features (location labels) seem more useful for video/tabletop game applications, while others (exporting to various formats) seem more useful for artistic endeavors such as the mentioned usage in Krita.

Feel free to close this issue! For the future, please remember to add reviewers to issues as well as pull requests.
