### ISSUE TITLE
[Deliverable 2]

### ISSUE THREAD

**Issue by cbondurant** [Berea-CS-Courses/capstone-project-cbondurant#5]
__One sentence overview of your submission__
Project decomposition

__I would like feedback on ...__ 
I totally forgot to make an issue for this one.

**Comment by jazzij** [comment]
Looks good! Very clear about the different sub-components and what needs to be implemented vs acquired or modified.

**Comment by walkerje** [comment]
Fantastic technically-oriented breakdown of system components and expectations. A sense of hierarchy is apparent through the breakdown analysis, however, explicitly setting priorities would better outline the order in which you intend to implement things. Mentioning what third-party libraries will be used would similarly be effective here as well (e.g, FastNoise), especially in relation to components that will use them. Similarly, what kind of formats do you intend to export things to (.png/.bmp/.tga/.dds or pretty much all common formats?) Thinking about the actual visual representation of this tool would be beneficial as well. You have the technical details, but an elaboration on user experience would strengthen the submission.

Feel free to close this issue!
